

h1=@(x,u,w) (pi^2*(exp(1i*(k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+exp(1i*(k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+exp(1i*(k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
    + pi^2*(exp(1i*(k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+exp(1i*(k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+exp(1i*(k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 +pi^2*(exp(1i*(k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+exp(1i*(k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+exp(1i*(k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(exp(1i*(k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+exp(1i*(k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+exp(1i*(k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))...
+ pi^2*(exp(1i*(-k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+exp(1i*(-k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+exp(1i*(-k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
 + pi^2*(exp(1i*(-k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+exp(1i*(-k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+exp(1i*(-k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 + pi^2*(exp(1i*(-k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+exp(1i*(-k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+exp(1i*(-k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(exp(1i*(-k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+exp(1i*(-k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+exp(1i*(-k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))).*x./(1+u.^2+w.^2).^(1/2);
 inth8=integral3(h1,0,1,0,1,0,1,'AbsTol',1e-8)
 toc
  tic
h1=@(x,u,w) (pi^2*(cos((k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+cos((k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+cos((k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
    + pi^2*(cos((k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+cos((k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+cos((k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 +pi^2*(cos((k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+cos((k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+cos((k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(cos((k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+cos((k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+cos((k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))...
+ pi^2*(cos((-k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+cos((-k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+cos((-k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
 + pi^2*(cos((-k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+cos((-k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+cos((-k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 + pi^2*(cos((-k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+cos((-k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+cos((-k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(cos((-k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+cos((-k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+cos((-k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))).*x./(1+u.^2+w.^2).^(1/2);
 inth9=integral3(h1,0,1,0,1,0,1,'AbsTol',1e-8)
 h1=@(x,u,w) (pi^2*(sin((k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+sin((k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+sin((k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
    + pi^2*(sin((k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+sin((k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+sin((k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 +pi^2*(sin((k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+sin((k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+sin((k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(sin((k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+sin((k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+sin((k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))...
+ pi^2*(sin((-k1*x*pi+k2*x.*u*pi+k3*x.*w*pi))+sin((-k1*x.*u*pi+k2*x.*w*pi+k3*x*pi))+sin((-k1*x.*w*pi+k2*x*pi+k3*x.*u*pi)))...
 + pi^2*(sin((-k1*x*pi+k2*x.*u*pi-k3*x.*w*pi))+sin((-k1*x.*u*pi+k2*x.*w*pi-k3*x*pi))+sin((-k1*x.*w*pi+k2*x*pi-k3*x.*u*pi)))...
 + pi^2*(sin((-k1*x*pi-k2*x.*u*pi+k3*x.*w*pi))+sin((-k1*x.*u*pi-k2*x.*w*pi+k3*x*pi))+sin((-k1*x.*w*pi-k2*x*pi+k3*x.*u*pi)))...
 +pi^2*(sin((-k1*x*pi-k2*x.*u*pi-k3*x.*w*pi))+sin((-k1*x.*u*pi-k2*x.*w*pi-k3*x*pi))+sin((-k1*x.*w*pi-k2*x*pi-k3*x.*u*pi)))).*x./(1+u.^2+w.^2).^(1/2);
 inth10=integral3(h1,0,1,0,1,0,1,'AbsTol',1e-8)
